id: P000654
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-16 15:57:26.913067
source_metadata:
  id: bdr:W29146
  title: རྩ་མདོའི་འགྲེལ་པ་བདུད་རྩིའི་ཟེགས་མ།
  author: ''
  volumes:
    d998fe3868f944f8bf59243ced604f2c:
      image_group_id: I1KG21774
      title: ''
      volume_number: 1
      total_pages: 144
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
