id: P000654
initial_creation_type: ocr
source_metadata:
  id: bdr:W29146
  title: རྩ་མདོའི་འགྲེལ་པ་བདུད་རྩིའི་ཟེགས་མ།
  author: ''
  volumes:
    d998fe3868f944f8bf59243ced604f2c:
      image_group_id: I1KG21774
      title: ''
      volume_number: 1
      total_pages: 144
