id: I5ED9BA4D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T17:06:37+00:00'
last_modified: '2022-06-07T12:33:58.753674+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29146
  title: རྩ་མདོའི་འགྲེལ་པ་བདུད་རྩིའི་ཟེགས་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '4014':
      image_group_id: I1KG21774
      title: ''
      total_pages: 144
      order: 1
      base_file: 4014.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
